name: Atlas Declarative CI - Databricks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
# Permissions to write comments on the pull request.
permissions:
  contents: read
  pull-requests: write
jobs:
  plan:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN }}
          version: 'beta'
      - uses: ariga/atlas-action/schema/plan@v1
        with:
          env: demo
          dev-url:  '${{ secrets.DATABRICKS_DEV_URL }}'
  push:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN }}
          version: 'beta'
      - uses: ariga/atlas-action/schema/plan/approve@v1
        id: plan-approve
        with:
          env: demo
          dev-url:  '${{ secrets.DATABRICKS_DEV_URL }}'
      - uses: ariga/atlas-action/schema/push@v1
        with:
          env: demo
          dev-url:  '${{ secrets.DATABRICKS_DEV_URL }}'
      - uses: ariga/atlas-action/schema/apply@v1
        with:
          env: demo
          dev-url:  '${{ secrets.DATABRICKS_DEV_URL }}'
          tx-mode: none